-- Estateo: base de datos pública para una landing dinámica.
-- Ejecuta este archivo una sola vez en Supabase > SQL Editor > New query.

-- BLOQUE 1: tablas que guardan el contenido visible en Angular.
-- site_settings solo admite la fila id = 1 porque representa la configuración
-- general de toda la página (título, imágenes, descripciones y precios).
create table public.site_settings (
  id bigint primary key default 1 check (id = 1),
  brand_name text not null,
  brand_tagline text not null,
  hero_prefix text not null,
  hero_accent text not null,
  hero_suffix text not null,
  hero_image_url text not null,
  section_badge text not null,
  section_title text not null,
  section_accent text not null,
  section_description text not null,
  investment_title text not null,
  investment_description text not null,
  investment_button text not null,
  sustainable_badge text not null,
  sustainable_title text not null,
  sustainable_description text not null,
  sustainable_image_url text not null,
  community_prices text[] not null default '{}',
  copyright_text text not null,
  updated_at timestamptz not null default now()
);

-- Lista ordenable de las tarjetas que aparecen sobre la portada.
create table public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  cta text not null default 'Find more',
  position integer not null default 1,
  updated_at timestamptz not null default now()
);

-- Tarjetas del bloque bento. variant decide entre dashboard y collaboration.
create table public.feature_cards (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  eyebrow text not null,
  variant text not null check (variant in ('dashboard', 'collaboration')),
  position integer not null default 1,
  updated_at timestamptz not null default now()
);

-- Enlaces del footer; group_name permite reunirlos en columnas.
create table public.footer_links (
  id bigint generated by default as identity primary key,
  group_name text not null,
  label text not null,
  url text not null default '#',
  position integer not null default 1,
  updated_at timestamptz not null default now()
);

-- BLOQUE 2: función y triggers para actualizar updated_at automáticamente
-- cada vez que se modifica una fila.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger site_settings_updated_at
before update on public.site_settings
for each row execute function public.set_updated_at();

create trigger services_updated_at
before update on public.services
for each row execute function public.set_updated_at();

create trigger feature_cards_updated_at
before update on public.feature_cards
for each row execute function public.set_updated_at();

create trigger footer_links_updated_at
before update on public.footer_links
for each row execute function public.set_updated_at();

-- BLOQUE 3: seguridad RLS. Primero se protege cada tabla y luego se crean
-- políticas que permiten SELECT público. No se permite escribir desde la web.
alter table public.site_settings enable row level security;
alter table public.services enable row level security;
alter table public.feature_cards enable row level security;
alter table public.footer_links enable row level security;

create policy "Public can read site settings" on public.site_settings
for select to anon, authenticated using (true);

create policy "Public can read services" on public.services
for select to anon, authenticated using (true);

create policy "Public can read feature cards" on public.feature_cards
for select to anon, authenticated using (true);

create policy "Public can read footer links" on public.footer_links
for select to anon, authenticated using (true);

-- BLOQUE 4: contenido inicial que se inserta al preparar la base de datos.
insert into public.site_settings (
  id, brand_name, brand_tagline, hero_prefix, hero_accent, hero_suffix, hero_image_url,
  section_badge, section_title, section_accent, section_description,
  investment_title, investment_description, investment_button,
  sustainable_badge, sustainable_title, sustainable_description, sustainable_image_url,
  community_prices, copyright_text
) values (
  1,
  'estateo',
  E'From property search\nto portfolio growth.',
  'Invest Today in',
  'a Dream',
  'House',
  '/assets/hero-house.webp',
  'PORTFOLIO TOOLS',
  'Omni-channel, any task,',
  'multi-language',
  'Assistant offers a human-like service that effortlessly blends in your process, completing nearly any tasks and collaborating with your team within the platform.',
  E'From single assets\nto a rental empire',
  'Our coordinated tools handle the complexities of property management, leaving you with a clear view of your portfolio and its growth.',
  'Start investing',
  'SUSTAINABLE',
  E'Smart homes.\nSmarter investments',
  'Data-driven insights to help you secure the best eco-homes for the short-term rental market. High demand. High returns.',
  '/assets/sustainable-community.webp',
  array['$920,000', '$832,500', '$959,000'],
  '© 2026 Estateo. All Rights Reserved'
);

insert into public.services (title, description, cta, position) values
  ('Smart Property', 'AI-powered analysis identifies properties with the highest capital growth potential based on market trends and long-term value drivers.', 'Find more', 1),
  ('Growth Forecasting', 'Predict future property value appreciation using data-driven forecasts, historical performance, and real-time market indicators.', 'Find more', 2),
  ('Portfolio Optimization', 'Build and balance a real estate portfolio designed to maximize long-term asset growth while managing risk across locations.', 'Find more', 3);

insert into public.feature_cards (title, description, eyebrow, variant, position) values
  ('Unified dashboard', 'Track all your properties, income, and growth metrics in one intuitive interface.', 'Market Trends', 'dashboard', 1),
  ('Collaborative', 'Specialized agents work together seamlessly to handle complex scenarios.', 'Live collaboration', 'collaboration', 2);

insert into public.footer_links (group_name, label, url, position) values
  ('Products', 'Investment Finder', '#', 1),
  ('Products', 'Rental Yield Calculator', '#', 2),
  ('Products', 'Portfolio Manager', '#', 3),
  ('Products', 'Market Heatmaps', '#', 4),
  ('Products', 'Tax Optimization', '#', 5),
  ('Customers', 'Investor Success Stories', '#', 1),
  ('Customers', 'Property Management Guide', '#', 2),
  ('Customers', 'Market Reports', '#', 3),
  ('Customers', 'Webinars', '#', 4),
  ('Company', 'About Us', '#', 1),
  ('Company', 'Partnership Program', '#', 2),
  ('Company', 'Legal Compliance', '#', 3),
  ('Company', 'Careers', '#', 4),
  ('Company', 'Contact Us', '#', 5);

-- BLOQUE 5: publica las tablas en Realtime para que ContentService reciba
-- eventos cuando ocurre un INSERT, UPDATE o DELETE.
alter publication supabase_realtime add table public.site_settings;
alter publication supabase_realtime add table public.services;
alter publication supabase_realtime add table public.feature_cards;
alter publication supabase_realtime add table public.footer_links;
